<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Event\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\Shared\ShippingPlatform.SharedKernel\ShippingPlatform.SharedKernel.csproj" />
    </ItemGroup>

</Project>
